/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NegativeEntry = IDL.Record({
  'entryType' : IDL.Text,
  'cellIndex' : IDL.Nat,
  'quantity' : IDL.Float64,
  'productIndex' : IDL.Nat,
  'reason' : IDL.Text,
});
export const SheetKey = IDL.Record({ 'date' : IDL.Text });
export const ProductRow = IDL.Record({
  'opening' : IDL.Float64,
  'productName' : IDL.Text,
  'delivery' : IDL.Float64,
  'transferCells' : IDL.Vec(IDL.Float64),
  'openCounter' : IDL.Float64,
  'additional' : IDL.Float64,
  'physical' : IDL.Float64,
  'transfer' : IDL.Float64,
  'posCount' : IDL.Float64,
  'deliveryCells' : IDL.Vec(IDL.Float64),
});
export const ReportRow = IDL.Record({
  'status' : IDL.Text,
  'reportLabel' : IDL.Text,
  'variance' : IDL.Float64,
});
export const DailySheet = IDL.Record({
  'negativeEntries' : IDL.Vec(NegativeEntry),
  'date' : IDL.Text,
  'rows' : IDL.Vec(ProductRow),
  'locked' : IDL.Bool,
  'negativeReasons' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'finalizedReport' : IDL.Opt(IDL.Vec(ReportRow)),
});
export const SheetValue = IDL.Record({ 'sheet' : DailySheet });
export const SheetEntry = IDL.Record({
  'key' : SheetKey,
  'value' : SheetValue,
});
export const ProductNameKey = IDL.Record({ 'index' : IDL.Nat });
export const ProductNameValue = IDL.Record({ 'name' : IDL.Text });
export const ProductNameEntry = IDL.Record({
  'key' : ProductNameKey,
  'value' : ProductNameValue,
});

export const idlService = IDL.Service({
  'getNegativeEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(NegativeEntry))],
      ['query'],
    ),
  'getProductName' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'loadAllSheets' : IDL.Func([], [IDL.Vec(SheetEntry)], ['query']),
  'loadProductNames' : IDL.Func([], [IDL.Vec(ProductNameEntry)], ['query']),
  'loadSheet' : IDL.Func([IDL.Text], [IDL.Opt(DailySheet)], ['query']),
  'lockSheet' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveProductNames' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveSheet' : IDL.Func([DailySheet], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NegativeEntry = IDL.Record({
    'entryType' : IDL.Text,
    'cellIndex' : IDL.Nat,
    'quantity' : IDL.Float64,
    'productIndex' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const SheetKey = IDL.Record({ 'date' : IDL.Text });
  const ProductRow = IDL.Record({
    'opening' : IDL.Float64,
    'productName' : IDL.Text,
    'delivery' : IDL.Float64,
    'transferCells' : IDL.Vec(IDL.Float64),
    'openCounter' : IDL.Float64,
    'additional' : IDL.Float64,
    'physical' : IDL.Float64,
    'transfer' : IDL.Float64,
    'posCount' : IDL.Float64,
    'deliveryCells' : IDL.Vec(IDL.Float64),
  });
  const ReportRow = IDL.Record({
    'status' : IDL.Text,
    'reportLabel' : IDL.Text,
    'variance' : IDL.Float64,
  });
  const DailySheet = IDL.Record({
    'negativeEntries' : IDL.Vec(NegativeEntry),
    'date' : IDL.Text,
    'rows' : IDL.Vec(ProductRow),
    'locked' : IDL.Bool,
    'negativeReasons' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'finalizedReport' : IDL.Opt(IDL.Vec(ReportRow)),
  });
  const SheetValue = IDL.Record({ 'sheet' : DailySheet });
  const SheetEntry = IDL.Record({ 'key' : SheetKey, 'value' : SheetValue });
  const ProductNameKey = IDL.Record({ 'index' : IDL.Nat });
  const ProductNameValue = IDL.Record({ 'name' : IDL.Text });
  const ProductNameEntry = IDL.Record({
    'key' : ProductNameKey,
    'value' : ProductNameValue,
  });
  
  return IDL.Service({
    'getNegativeEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(NegativeEntry))],
        ['query'],
      ),
    'getProductName' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'loadAllSheets' : IDL.Func([], [IDL.Vec(SheetEntry)], ['query']),
    'loadProductNames' : IDL.Func([], [IDL.Vec(ProductNameEntry)], ['query']),
    'loadSheet' : IDL.Func([IDL.Text], [IDL.Opt(DailySheet)], ['query']),
    'lockSheet' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveProductNames' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveSheet' : IDL.Func([DailySheet], [], []),
  });
};

export const init = ({ IDL }) => { return []; };