/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StockEntry = IDL.Record({
  'receivedQty' : IDL.Float64,
  'productId' : IDL.Nat,
  'actualClosing' : IDL.Float64,
  'soldQty' : IDL.Float64,
  'openingStock' : IDL.Float64,
});
export const Session = IDL.Record({
  'sessionType' : IDL.Text,
  'entries' : IDL.Vec(StockEntry),
  'savedAt' : IDL.Int,
});
export const DailySheet = IDL.Record({
  'date' : IDL.Text,
  'isClosed' : IDL.Bool,
  'closedAt' : IDL.Opt(IDL.Int),
  'sessions' : IDL.Vec(Session),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
});

export const idlService = IDL.Service({
  'closeDay' : IDL.Func([IDL.Text], [], []),
  'getAllStockForDay' : IDL.Func([IDL.Text], [IDL.Vec(StockEntry)], ['query']),
  'getClosedDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDailySheet' : IDL.Func([IDL.Text], [IDL.Opt(DailySheet)], ['query']),
  'getDaysByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(IDL.Text)], ['query']),
  'getDiffForDay' : IDL.Func([IDL.Text], [IDL.Vec(StockEntry)], ['query']),
  'getOpeningStockForNewDay' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockEntry)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'initializeProducts' : IDL.Func([], [], []),
  'saveSession' : IDL.Func([IDL.Text, Session], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StockEntry = IDL.Record({
    'receivedQty' : IDL.Float64,
    'productId' : IDL.Nat,
    'actualClosing' : IDL.Float64,
    'soldQty' : IDL.Float64,
    'openingStock' : IDL.Float64,
  });
  const Session = IDL.Record({
    'sessionType' : IDL.Text,
    'entries' : IDL.Vec(StockEntry),
    'savedAt' : IDL.Int,
  });
  const DailySheet = IDL.Record({
    'date' : IDL.Text,
    'isClosed' : IDL.Bool,
    'closedAt' : IDL.Opt(IDL.Int),
    'sessions' : IDL.Vec(Session),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  
  return IDL.Service({
    'closeDay' : IDL.Func([IDL.Text], [], []),
    'getAllStockForDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockEntry)],
        ['query'],
      ),
    'getClosedDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDailySheet' : IDL.Func([IDL.Text], [IDL.Opt(DailySheet)], ['query']),
    'getDaysByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(IDL.Text)], ['query']),
    'getDiffForDay' : IDL.Func([IDL.Text], [IDL.Vec(StockEntry)], ['query']),
    'getOpeningStockForNewDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockEntry)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'initializeProducts' : IDL.Func([], [], []),
    'saveSession' : IDL.Func([IDL.Text, Session], [], []),
  });
};

export const init = ({ IDL }) => { return []; };