/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySheet {
  'negativeEntries' : Array<NegativeEntry>,
  'date' : string,
  'rows' : Array<ProductRow>,
  'locked' : boolean,
  'negativeReasons' : Array<[string, string]>,
  'finalizedReport' : [] | [Array<ReportRow>],
}
export interface NegativeEntry {
  'entryType' : string,
  'cellIndex' : bigint,
  'quantity' : number,
  'productIndex' : bigint,
  'reason' : string,
}
export interface ProductNameEntry {
  'key' : ProductNameKey,
  'value' : ProductNameValue,
}
export interface ProductNameKey { 'index' : bigint }
export interface ProductNameValue { 'name' : string }
export interface ProductRow {
  'opening' : number,
  'productName' : string,
  'delivery' : number,
  'transferCells' : Array<number>,
  'openCounter' : number,
  'additional' : number,
  'physical' : number,
  'transfer' : number,
  'posCount' : number,
  'deliveryCells' : Array<number>,
}
export interface ReportRow {
  'status' : string,
  'reportLabel' : string,
  'variance' : number,
}
export interface SheetEntry { 'key' : SheetKey, 'value' : SheetValue }
export interface SheetKey { 'date' : string }
export interface SheetValue { 'sheet' : DailySheet }
export interface _SERVICE {
  'getNegativeEntries' : ActorMethod<[string], [] | [Array<NegativeEntry>]>,
  'getProductName' : ActorMethod<[bigint], [] | [string]>,
  'loadAllSheets' : ActorMethod<[], Array<SheetEntry>>,
  'loadProductNames' : ActorMethod<[], Array<ProductNameEntry>>,
  'loadSheet' : ActorMethod<[string], [] | [DailySheet]>,
  'lockSheet' : ActorMethod<[string], boolean>,
  'saveProductNames' : ActorMethod<[Array<string>], undefined>,
  'saveSheet' : ActorMethod<[DailySheet], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];