/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySheet {
  'date' : string,
  'isClosed' : boolean,
  'closedAt' : [] | [bigint],
  'sessions' : Array<Session>,
}
export interface Product { 'id' : bigint, 'name' : string, 'unit' : string }
export interface Session {
  'sessionType' : string,
  'entries' : Array<StockEntry>,
  'savedAt' : bigint,
}
export interface StockEntry {
  'receivedQty' : number,
  'productId' : bigint,
  'actualClosing' : number,
  'soldQty' : number,
  'openingStock' : number,
}
export interface _SERVICE {
  'closeDay' : ActorMethod<[string], undefined>,
  'getAllStockForDay' : ActorMethod<[string], Array<StockEntry>>,
  'getClosedDates' : ActorMethod<[], Array<string>>,
  'getDailySheet' : ActorMethod<[string], [] | [DailySheet]>,
  'getDaysByStatus' : ActorMethod<[boolean], Array<string>>,
  'getDiffForDay' : ActorMethod<[string], Array<StockEntry>>,
  'getOpeningStockForNewDay' : ActorMethod<[string], Array<StockEntry>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'initializeProducts' : ActorMethod<[], undefined>,
  'saveSession' : ActorMethod<[string, Session], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];