/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductRow {
    opening: number;
    productName: string;
    delivery: number;
    transferCells: Array<number>;
    openCounter: number;
    additional: number;
    physical: number;
    transfer: number;
    posCount: number;
    deliveryCells: Array<number>;
}
export interface ProductNameKey {
    index: bigint;
}
export interface ProductNameEntry {
    key: ProductNameKey;
    value: ProductNameValue;
}
export interface DailySheet {
    negativeEntries: Array<NegativeEntry>;
    date: string;
    rows: Array<ProductRow>;
    locked: boolean;
    negativeReasons: Array<[string, string]>;
    finalizedReport?: Array<ReportRow>;
}
export interface NegativeEntry {
    entryType: string;
    cellIndex: bigint;
    quantity: number;
    productIndex: bigint;
    reason: string;
}
export interface SheetEntry {
    key: SheetKey;
    value: SheetValue;
}
export interface SheetKey {
    date: string;
}
export interface ReportRow {
    status: string;
    reportLabel: string;
    variance: number;
}
export interface SheetValue {
    sheet: DailySheet;
}
export interface ProductNameValue {
    name: string;
}
export interface backendInterface {
    getNegativeEntries(date: string): Promise<Array<NegativeEntry> | null>;
    getProductName(index: bigint): Promise<string | null>;
    loadAllSheets(): Promise<Array<SheetEntry>>;
    loadProductNames(): Promise<Array<ProductNameEntry>>;
    loadSheet(date: string): Promise<DailySheet | null>;
    lockSheet(date: string): Promise<boolean>;
    saveProductNames(names: Array<string>): Promise<void>;
    saveSheet(sheet: DailySheet): Promise<void>;
}
import type { DailySheet as _DailySheet, NegativeEntry as _NegativeEntry, ProductRow as _ProductRow, ReportRow as _ReportRow, SheetEntry as _SheetEntry, SheetKey as _SheetKey, SheetValue as _SheetValue } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getNegativeEntries(arg0: string): Promise<Array<NegativeEntry> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNegativeEntries(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNegativeEntries(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductName(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductName(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductName(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadAllSheets(): Promise<Array<SheetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.loadAllSheets();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadAllSheets();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadProductNames(): Promise<Array<ProductNameEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.loadProductNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadProductNames();
            return result;
        }
    }
    async loadSheet(arg0: string): Promise<DailySheet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loadSheet(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadSheet(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockSheet(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.lockSheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockSheet(arg0);
            return result;
        }
    }
    async saveProductNames(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProductNames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProductNames(arg0);
            return result;
        }
    }
    async saveSheet(arg0: DailySheet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSheet(to_candid_DailySheet_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSheet(to_candid_DailySheet_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DailySheet_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailySheet): DailySheet {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SheetEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SheetEntry): SheetEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SheetValue_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SheetValue): SheetValue {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_NegativeEntry>]): Array<NegativeEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ReportRow>]): Array<ReportRow> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailySheet]): DailySheet | null {
    return value.length === 0 ? null : from_candid_DailySheet_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    key: _SheetKey;
    value: _SheetValue;
}): {
    key: SheetKey;
    value: SheetValue;
} {
    return {
        key: value.key,
        value: from_candid_SheetValue_n6(_uploadFile, _downloadFile, value.value)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sheet: _DailySheet;
}): {
    sheet: DailySheet;
} {
    return {
        sheet: from_candid_DailySheet_n8(_uploadFile, _downloadFile, value.sheet)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negativeEntries: Array<_NegativeEntry>;
    date: string;
    rows: Array<_ProductRow>;
    locked: boolean;
    negativeReasons: Array<[string, string]>;
    finalizedReport: [] | [Array<_ReportRow>];
}): {
    negativeEntries: Array<NegativeEntry>;
    date: string;
    rows: Array<ProductRow>;
    locked: boolean;
    negativeReasons: Array<[string, string]>;
    finalizedReport?: Array<ReportRow>;
} {
    return {
        negativeEntries: value.negativeEntries,
        date: value.date,
        rows: value.rows,
        locked: value.locked,
        negativeReasons: value.negativeReasons,
        finalizedReport: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.finalizedReport))
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SheetEntry>): Array<SheetEntry> {
    return value.map((x)=>from_candid_SheetEntry_n4(_uploadFile, _downloadFile, x));
}
function to_candid_DailySheet_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailySheet): _DailySheet {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negativeEntries: Array<NegativeEntry>;
    date: string;
    rows: Array<ProductRow>;
    locked: boolean;
    negativeReasons: Array<[string, string]>;
    finalizedReport?: Array<ReportRow>;
}): {
    negativeEntries: Array<_NegativeEntry>;
    date: string;
    rows: Array<_ProductRow>;
    locked: boolean;
    negativeReasons: Array<[string, string]>;
    finalizedReport: [] | [Array<_ReportRow>];
} {
    return {
        negativeEntries: value.negativeEntries,
        date: value.date,
        rows: value.rows,
        locked: value.locked,
        negativeReasons: value.negativeReasons,
        finalizedReport: value.finalizedReport ? candid_some(value.finalizedReport) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
