/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    sessionType: string;
    entries: Array<StockEntry>;
    savedAt: bigint;
}
export interface DailySheet {
    date: string;
    isClosed: boolean;
    closedAt?: bigint;
    sessions: Array<Session>;
}
export interface Product {
    id: bigint;
    name: string;
    unit: string;
}
export interface StockEntry {
    receivedQty: number;
    productId: bigint;
    actualClosing: number;
    soldQty: number;
    openingStock: number;
}
export interface backendInterface {
    closeDay(date: string): Promise<void>;
    getAllStockForDay(date: string): Promise<Array<StockEntry>>;
    getClosedDates(): Promise<Array<string>>;
    getDailySheet(date: string): Promise<DailySheet | null>;
    getDaysByStatus(isClosed: boolean): Promise<Array<string>>;
    getDiffForDay(date: string): Promise<Array<StockEntry>>;
    getOpeningStockForNewDay(date: string): Promise<Array<StockEntry>>;
    getProducts(): Promise<Array<Product>>;
    initializeProducts(): Promise<void>;
    saveSession(date: string, session: Session): Promise<void>;
}
import type { DailySheet as _DailySheet, Session as _Session } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async closeDay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeDay(arg0);
            return result;
        }
    }
    async getAllStockForDay(arg0: string): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockForDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockForDay(arg0);
            return result;
        }
    }
    async getClosedDates(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedDates();
            return result;
        }
    }
    async getDailySheet(arg0: string): Promise<DailySheet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySheet(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySheet(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDaysByStatus(arg0: boolean): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDaysByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDaysByStatus(arg0);
            return result;
        }
    }
    async getDiffForDay(arg0: string): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiffForDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiffForDay(arg0);
            return result;
        }
    }
    async getOpeningStockForNewDay(arg0: string): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpeningStockForNewDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpeningStockForNewDay(arg0);
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async initializeProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeProducts();
            return result;
        }
    }
    async saveSession(arg0: string, arg1: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSession(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DailySheet_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailySheet): DailySheet {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailySheet]): DailySheet | null {
    return value.length === 0 ? null : from_candid_DailySheet_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    isClosed: boolean;
    closedAt: [] | [bigint];
    sessions: Array<_Session>;
}): {
    date: string;
    isClosed: boolean;
    closedAt?: bigint;
    sessions: Array<Session>;
} {
    return {
        date: value.date,
        isClosed: value.isClosed,
        closedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.closedAt)),
        sessions: value.sessions
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
